### ISSUE TITLE
merging NETIF into this

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/networking#15]
Is it worth considering merging the NETIF code into this repo?

then I think we could add the helics functions to find the external interfaces into this library as well.  I am not sure what that would mean for testing though.  I added a disable ASIO option so conceivable they current NETIF tests could move over and use that option on the platforms that asio doesn't work on.

**Comment by nightlark** [comment]
We could also just submodule/vendor it.

**Comment by phlptp** [comment]
Looking at the code the functions that use NetIF are all not fundamental to HELICS and might be useful elsewhere.  Those functions all require some other capabilities that have been migrated to the networking library.    So I am struggling with whether the NetIF library is valuable on its own right now or whether it is value in conjuction with the networking library.  And whether that value justifies the additional complexity of maintaining 2 libraries vs 1?

**Comment by nightlark** [comment]
The functions that use NetIF in HELICS should be moved to the networking library.

I think there is value (though maybe niche) in having a header-only library that is network library-agnostic that can be used independently of Asio or another networking library. It fills the same function as https://pkg.go.dev/net#Interfaces + https://pkg.go.dev/net#Interface.Addrs for enumerating addresses on multiple interfaces that Asio and other C++ networking libraries don't have an equivalent to, which makes things like sending a multicast packet to both wired and wireless networks from a laptop or multi-NIC setups awkward, or giving a user a list of addresses on their system to choose from.

**Comment by phlptp** [comment]
So you think the best path might be to drop NetIF from HELICS but include it as a submodule in the networking library?

**Comment by nightlark** [comment]
Yea, definitely drop it from HELICS, and I think for now include it as a submodule in the networking library.

If the netif source tree later gets merged into the networking repo, I think I'd want to have it set up so the namespace stays the same and some docs(README)/CI jobs come along with it; then links could be easily updated to point to the new subtree.

**Comment by phlptp** [comment]
ok, in PR #16 I add NetIF as a submodule and moved over some more functions and tests.
